[package]
name = "project-madness"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = {version = "0.17", features = ["file_watcher"]}
bevy_aseprite_ultra = "0.7.0"
bevy_ecs_ldtk = "0.13.0"
bevy_tweening = "0.14"
bladeink = "1.2.1"
rand = "0.9.2"
